debug: false # Turn to 'true' when asked for debugging information
store_identifier: 411486491630370816
apollo_hook: true # Set to true to enable Lunar Client IFrame checkout support
npc_hook: auto # auto, fancynpcs, citizens
donation_npc_update_every: 60 # Seconds

cancel_url: "https://kyllian.nl/discord"
return_url: "https://kyllian.nl/discord" # After successful purchase, the user will be redirected here

recent_donator_npc:
  enabled: false
  hologram: |-
    &d&lMOST RECENT DONATOR
    %packages%
    &e&l%name% &7(&a&l%total%&7)
  package_format: "&8- &7%name% &d&l%amount%"
  update_every: 60 # Seconds
  npc_id: 99 # Citizens ID or FancyNpcs name/id

top_donator_all_time_npc:
  enabled: false
  hologram: |-
    &d&lTOP DONATOR
    &7All Time
    &e&l%name% &7(&a&l%total%&7)
  npc_id: top-donator-all-time # Citizens ID or FancyNpcs name/id

top_donator_month_npc:
  enabled: false
  hologram: |-
    &d&lTOP DONATOR
    &7This Month
    &e&l%name% &7(&a&l%total%&7)
  npc_id: top-donator-this-month # Citizens ID or FancyNpcs name/id

tags_gui:
  title: "my.store.net"
  size: 18
  tag_item:
    name: "&e&l%tag%"
    material: CHEST
    slots: [0, 1, 2, 3, 4, 5, 6, 7, 8]
    overrides:
      "1234": # Tag ID
        material: DIAMOND_CHESTPLATE
        name: "&c%tag%"
        lore: |-
          &cSpecial!
        custom_model_data: 1234567
  checkout_item:
    slot: 13
    line_template: "&8- &7%item% &8&l(&2$%price%&8&l) &fx%amount%"
    loading:
      material: BARRIER
      name: "&f&lCheckout"
      lore: |-
        &7Loading your cart...
    empty:
      material: MINECART
      name: "&f&lCheckout"
      lore: |-
        &cYour cart is empty!
    filled:
      material: CHEST_MINECART
      name: "&f&lCheckout"
      lore: |-
        %items%
        &7Cart total: &a&l$%cartprice%
        &eClick to check out on our website
    filled_lunar:
      material: CHEST_MINECART
      name: "&f&lCheckout"
      lore: |-
        %items%
        &7Cart total: &a&l$%cartprice%
        &eLeft-click to check out with Lunar Client
        &eRight-click to check out on our website
  clear_cart_item: # Clicking this item will clear the cart
    slots: "12,14"
    material: BARRIER
    name: "&c&lClear Cart"
    lore: |-
      &r
      &7Clicking this will &c&lclear &7your cart!

products_gui:
  title: "%tag%"
  size: 0 # 0 = Dynamically size based on amount of products. Other = Fixed size (9, 18, 27, 36, 45, 54) Useful for texturing
  item: # Material is gathered from 'products.yml'
    material_max_quantity: BARRIER
    lore: |-
      &7Price &2&l$%price%
      &7In cart: &e&l%amount%
      &r
      &7Left-Click to &a&ladd &7to your cart (+1)
      &7Right-Click to &c&lremove &7from your cart (-1)
      &7Shift Right-Click to &c&lremove all &7from your cart
      &r
      &8&o(Prices may vary when tax is applied)
  back_item:
    material: FEATHER
    name: "&c&lBack"
    lore: ""

select_server_gui:
  title: "Select server"
  type: HOPPER # Interchangeable with 'slot: 9' etc...
  items:
    store_id: # Use the gameServerID as the key
      slot: 0
      material: DIAMOND_SWORD
      name: "&cLorem Ipsum"
      lore: |-
        &7Click to select the Lorem Ipsum server

messages:
  error: "&cAn error occurred while trying to process your request. Please try again later."
  checkout_link: "&7[here]"
  checkout_website: |-
    &f&m                                    &7
    &r
    &aTo purchase your cart, click %link%&a!
    &r
    &f&m                                    &7
  wait: "&cPlease wait while we load the data..."
